export const GAME_SET_SETTINGS = 'GAME_SET_SETTINGS'
export const GAME_CREATE = 'GAME_CREATE'
export const GAME_START = 'GAME_START'
export const GAME_UPDATE_FLAGS = 'GAME_UPDATE_FLAGS'
export const GAME_WIN = 'GAME_WIN'
export const GAME_LOSE = 'GAME_LOSE'
export const GAME_SWEEP = 'GAME_SWEEP'
export const UI_TOGGLE_MODAL = 'UI_TOGGLE_MODAL'
